version: "3.9"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx/html:/usr/share/nginx/html
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: mariadb:latest
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  backend:
    build: ./back
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: java -jar ./app.jar
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
