version: "3.9"

services:
   db:
    image: mariadb:latest
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  backend:
    build: .
    expose:
      - 8080
    command: java -jar ./app.jar
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
